site_name: EasyDel

copyright: "Erfan Zare Chavoshi-EasyDel"
nav:
  - Home: index.md
  - Install: Install.md
  - AvailableModels: AvailableModels.md
  - EasyBIT: Bits.md
  - Eval:
      - lm_eval: eval-lm_eval.md
  - Transform:
      - easydel_transform: transform-easydel_transform.md
      - mpt: transform-mpt.md
      - llama: transform-llama.md
      - falcon: transform-falcon.md
      - mistral: transform-mistral.md
      - utils: transform-utils.md
  - smi: smi-smi.md
  - Serve:
      - torch_serve: serve-torch_serve.md
      - jax_serve: serve-jax_serve.md
      - utils: serve-utils.md
  - Modules:
      - Falcon: modules-falcon-modelling_falcon_flax.md
      - Palm: modules-palm-modelling_palm_flax.md
      - flax_modelling_utils: modules-flax_modelling_utils.md
      - GPT-Neox: modules-gpt_neo_x-modelling_gpt_neo_x_flax.md
      - GPT-J: modules-gpt_j-modelling_gpt_j_flax.md
      - Mistral: modules-mistral-modelling_mistral_flax.md
      - auto_models: modules-auto_models.md
      - LucidTransformers: modules-lucid_transformer-modelling_lt_flax.md
      - OPT: modules-opt-modelling_opt_flax.md
      - MPT: modules-mosaic_mpt-modelling_mpt_flax.md
      - Llama: modules-llama-modelling_llama_flax.md
      - Mixtral: modules-mixtral-modelling_mixtral_flax.md
      - PHI: modules-phi-modelling_phi_flax.md
      - T5: modules-t5-modelling_t5_flax.md
  - Etils:
      - configs: etils-configs.md
      - Errors: etils-errors.md
      - Etils: etils-etils.md
  - Utils:
      - tensor_utils: utils-tensor_utils.md
      - prompters: utils-prompters.md
      - utils: utils-utils.md
      - checker: utils-checker.md
  - RLHF:
      - trainer: rlhf-trainer.md
      - reward: rlhf-reward.md
      - ppo: rlhf-ppo.md
      - utils: rlhf-utils.md

  - Trainer:
      - fsdp_train: trainer-fsdp_train.md
      - config: trainer-config.md
      - tf_dataset: trainer-tf_dataset.md
      - training_utils: trainer-training_utils.md
  - Linen:
      - bits: linen-bits.md
      - utils: linen-utils.md
  - RL Trainer:
      core: rl_trainer-core.md
      models:
        modelling_base: rl_trainer-models-modelling_base.md
        modelling_value_head: rl_trainer-models-modelling_value_head.md
      trainer:
        base: rl_trainer-trainer-base.md
        ppo_trainer: rl_trainer-trainer-ppo_trainer.md
  - Data Preprocessing:
      - data_preprocessing/_processor: data_preprocessing-_processor.md
  - Examples:
      - PytorchServer: PyTorchServer.md
      - JAXServer: JAXServer.md
      - DataProcessing: DataProcessing.md
      - TrainingExample: TrainingExample.md
      - Falcon Models: Falcon.md
      - Llama Models: Llama.md
      - Llama2 Models: Llama2.md
      - Mistral Models: Mistral.md
      - MosaicMPT Models: MosaicMPT.md

site_author: "Erfan Zare Chavoshi"
repo_url: "https://github.com/erfanzar/EasyDel"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - python
