[project]
name = "EasyDeL"
authors = [{ name = "Erfan Zare Chavoshi", email = "Erfanzare810@gmail.com" }]
requires-python = ">=3.8"
readme = "README.md"
version = "0.0.68"
dependencies = [
    "jax>=0.4.20",
    "jaxlib>=0.4.20",
    "fjformer==0.0.64",
    "transformers>=4.40.0",
    "optax~=0.1.7",
    "msgpack~=1.0.7",
    "ipython~=8.17.2",
    "tqdm~=4.64.1",
    "datasets~=2.14.6",
    "tensorboard",
    "numpy~=1.26.2",
    "tensorflow~=2.16.1",
    "tensorflow_datasets>=4.9.0",
    "scipy==1.13.1",
    "websocket-client",
    "websockets"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
description = "An open-source library to make training faster and more optimized in Jax/Flax"
license = { text = "Apache-2.0" }
keywords = ["JAX", "Torch", "Deep Learning", "Machine Learning", "Flax", "XLA"]

[project.optional-dependencies]
torch = ["torch", "torchvision", "torchaudio"]
all = ["EasyDeL[torch]"]

[project.urls]
Homepage = "https://github.com/erfanzar/EasyDeL"
Issues = "https://github.com/erfanzar/EasyDeL/issues"
Documentation = "https://erfanzar.github.io/EasyDeL"

[tool.hatch.build]
include = ["*.py"]
dev-mode-dirs = [".", "src"]

[tool.hatch.build.sources]
"src/easydel" = "easydel"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["easydel"]


[tool.black]
line-length = 88
target-version = ["py310"]
preview = true

[tool.isort]
profile = "black"
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
src_paths = ["src"]
known_haliax = ["haliax"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "HALIAX", "FIRSTPARTY", "LOCALFOLDER"]

[tool.mypy]
python_version = "3.10"
mypy_path = ["src"]

[tool.mypy-haliax.core]
ignore_missing_imports = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"